# Generated by Django 5.0.7 on 2024-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=" ", null=True, unique=True),
        ),
    ]
